name: Login to Fly.io

on:
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  login-to-fly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          sudo mv flyctl /usr/local/bin/
          flyctl --version # Verify the installation
        env:
          FLYCTL_INSTALL_WAIT: true

      - name: Login to Fly.io with Access Token
        run: |
          flyctl auth login -t ${{ secrets.FLY_ACCESS_TOKEN }}
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
